### ISSUE TITLE
How to install without the .zxp file, as this last release?

### ISSUE THREAD

**Issue by Leomaker** [TomByrne/Flash2Svg#10]

**Comment by TomByrne** [comment]
I don't understand the question.
You can either install from the Adobe Add-ons site or download from the Releases section here on Github and install with Extension Manager (or ExtManCmd).

**Comment by Leomaker** [comment]
I can't find the .zxp in the Releases section in the latest release:
![GitHub Logo](http://s3.postimg.org/lhwsj1cyb/v331.png)

In the .zip folder I found .bat file inside,
![GitHub Logo](http://s24.postimg.org/ba03mmg0l/build.png)
but I don't know how to install yet. 

Sorry for my ignorance and thank you for the help.

**Comment by TomByrne** [comment]
I've fixed v3.31 release and added v3.32
