### ISSUE TITLE
Error: TypeError: timeline.libraryItem is null

### ISSUE THREAD

**Issue by antoniocosta** [TomByrne/Flash2Svg#11]
When exporting output type SVG images I keep getting the error TypeError: timeline.libraryItem is null 
Animated SVG works fine though.

Flash2Svg.v3.33.0
Flash 2015.0 Release Build 15.0.1.179

**Comment by TomByrne** [comment]
Would you be able to send me the FLA you are trying to export?

**Comment by antoniocosta** [comment]
Sure. Attached one.
Please keep in mind that you have to select "SVG Images" as Output Format Type (instead of "Animated SVG")
[arrow.fla.zip](https://github.com/TomByrne/Flash2Svg/files/99334/arrow.fla.zip)

**Comment by TomByrne** [comment]
This issue is resolved in v3.36
