### ISSUE TITLE
SMIL SVG animations can now play on all browsers thanks to this polyfill

### ISSUE THREAD

**Issue by Emasoft** [TomByrne/Flash2Svg#13]
SMIL SVG animations can now play on all browsers thanks to this polyfill:

https://github.com/ericwilligers/svg-animation

You should add that info to the readme!

**Comment by TomByrne** [comment]
I've had a look at that polyfill, but it looks like it might still be a little early for production use.

Here are some examples of it in use (with exports from Flash2Svg) so you can see it's behaviour in IE/Edge.

Without Polyfill:
http://www.tbyrne.org/staging/smil-polyfill/tears.htm

With Polyfill:
http://www.tbyrne.org/staging/smil-polyfill/tears_polyfill.htm

**Comment by Emasoft** [comment]
Great demos, thank you! You should include more demos like this as examples in the readme!
