### ISSUE TITLE
Primitives and Drawing objects need to be broken apart to export properly

### ISSUE THREAD

**Issue by jarkkosyrjala** [TomByrne/Flash2Svg#16]
Drawing objects are not being exported correctly. Tested using Animate CC (2015.1 release).

Here's an example FLA with generated SVG:
[flash2svg_bug_test.fla.zip](https://github.com/TomByrne/Flash2Svg/files/204543/flash2svg_bug_test.fla.zip)
Example has two Movieclips on stage. Lower one is the original that has been drawn using drawing objects and and oval primitive and the upper one where all shapes have been broken apart (Modify>Break Apart).

Result should have two identical Pacmans, but the lower (original with primitives and Drawing objects inside) gets corrupted. The upper pacman is exported correctly (All shapes inside it have been broken apart).

This is what should be exported:
![image](https://cloud.githubusercontent.com/assets/1029627/14283499/55184d20-fb4c-11e5-8f67-189e570f2ba1.png)

But this is what gets exported:
![image](https://cloud.githubusercontent.com/assets/1029627/14283642/c9d27442-fb4c-11e5-8a64-816a2fc374cf.png)

**Comment by TomByrne** [comment]
A fix for this will be included in v3.51
