### ISSUE TITLE
Requires Flash 11 or above, but I have that

### ISSUE THREAD

**Issue by ghost** [TomByrne/Flash2Svg#17]
Hey

I get this error when I try to install the extension:

![screen shot 2016-05-20 at 13 29 14](https://cloud.githubusercontent.com/assets/15079453/15427730/f1fd81fe-1e8e-11e6-940a-a2d94932243a.png)

But I have latest Flash CC.

![screen shot 2016-05-20 at 13 29 27](https://cloud.githubusercontent.com/assets/15079453/15427752/02eefe3e-1e8f-11e6-9cf6-9c5de958b19b.png)

So, umm ... help? =)

**Comment by TomByrne** [comment]
This is really an issue with Adobe's plugin system, and it's surprisingly common.
I'd either get in contact with Adobe or use the manual install process from my blog:
http://www.tbyrne.org/manually-installing-flash2svg

**Comment by ghost** [comment]
Yeah, I ended up manually installing.

Just a little request, for others, can you please add a link to manual install to the release page https://github.com/TomByrne/Flash2Svg/releases simply to save headaches and people Googling only to basically end up back at you =)
