### ISSUE TITLE
Link is wrong

### ISSUE THREAD

**Issue by ghost** [TomByrne/Flash2Svg#19]
Hey mate,

the link here
![screen shot 2016-07-05 at 13 05 07](https://cloud.githubusercontent.com/assets/15079453/16584009/22f80d42-42b1-11e6-94d9-ca2247237ccb.png)

Is linking to the wrong article. It should link here

http://www.tbyrne.org/manually-installing-flash2svg

**Comment by TomByrne** [comment]
Cheers mate
