### ISSUE TITLE
Motion Tween not implemented

### ISSUE THREAD

**Issue by ahbox** [TomByrne/Flash2Svg#20]
Dear author,

I read your readme information and noticed that the classic motion tween is already supported. However I created a test FLA document and noticed that the motion tween is not working. The keyframe-animations did work.

In the attachment I've put the FLA and SVG files.

[test-animation.zip](https://github.com/TomByrne/Flash2Svg/files/371807/test-animation.zip)

Thanks,

**Comment by TomByrne** [comment]
The newer style of Motion Tweens will be converted to keyframes and exported this way.
Your test animation seemed to export fine for me.
[testanimation-export.zip](https://github.com/TomByrne/Flash2Svg/files/373416/testanimation-export.zip)
