### ISSUE TITLE
TypeError: timeline is undefined

### ISSUE THREAD

**Issue by vif-maureen** [TomByrne/Flash2Svg#21]
When trying to use this add-on to export an animation I get the error:

`TypeError: timeline is undefined`

I had the issue when installing from the Adobe Add-on page and thought I needed to update to your latest release. But I get the same results either way. (You might want to update the version that is on the Adobe site to your latest).

Are there any guidelines as far as nesting movie clips or anything that needs to be done to work more efficiently with it? I was able to export one animation but I'm not sure why one worked and not the other. Could be I'm missing something obvious.

Using Mac OSX 10.11.6, Adobe Animate CC 2015.2

I have to make at least 6 animations for an upcoming deadline and really hoping to get this t work. Thanks for any advice. Here's my file if it helps!

[Homepage.fla.zip](https://github.com/TomByrne/Flash2Svg/files/437670/Homepage.fla.zip)

**Comment by vif-maureen** [comment]
I was able to fix this by downgrading to Animate 2015.1. Thanks.

**Comment by TomByrne** [comment]
I've looked into this and there appears to be an issue with the Convert Text to Outlines feature.
As far as I can tell this is an issue that affects all versions of Flash/Animate.
Please avoid using this feature till I've had a chance to fix it.

**Comment by vif-maureen** [comment]
Tom, thank you for looking into this. 

I have also found that for complex animations, it helps to export some of the layers separately and combine the code in something like codepen in case you need to make adjustments to get everything working right.

Thanks for a great plugin - this is saving my life with a huge project I'm working on!

**Comment by TomByrne** [comment]
The fix for this will be released in v3.51
