### ISSUE TITLE
Getting error on export

### ISSUE THREAD

**Issue by imjusthere** [TomByrne/Flash2Svg#23]
I'm getting the following error whenever I try to export as svg:

TypeError: svgXml.defs[0] has no properties

Any idea why? I'm using Flash Professional CS6 version 12.0.0.481 and your plugin v3.47.0

Warmest regards,
Chris

**Comment by montrealist** [comment]
Can't help here, but it would likely help to include a link to the (zipped) FLA in question for others to look at.

**Comment by TomByrne** [comment]
Hey Chris,
As noted on the project page, the last version that works in CS5.5 and CS6 is v3.36.
