### ISSUE TITLE
Animate CC 2015.2 installation error

### ISSUE THREAD

**Issue by deepstroke** [TomByrne/Flash2Svg#25]
Not working with the latest version.

Adobe extension manager gives this error:
"This extension can not be installed, it requires Flash version 11 or greater"

But It can be installed with ExMan Command Line Tool
https://www.adobeexchange.com/resources/28

Thanks for this great tool

**Comment by TomByrne** [comment]
This really is an issue with Adobe's plugin system, unless I create my own plugin installer there's not much to be done about this.
