### ISSUE TITLE
Render issues - lines overlapping or errors thrown left right and centre 

### ISSUE THREAD

**Issue by elgamble** [TomByrne/Flash2Svg#26]
Hello there,

I'm having a few issues rendering with the svg exporter in flash cc.

Basically the animation is frame by frame, a few classic tweens thrown in there for good measure. At first I tried exporting the file from within the graphic where all the layers were nested. this did not work and merely broke all the different objects up and the render was not successful.

I then went into the main timeline, broke up all the objects and this kind of works... but the lines overlap as if onion skin is on? It's only at one specific point too; where there's a bit of hand drawn animation. 

can anybody help? Will happily send over working files if needed

Cheers

**Comment by TomByrne** [comment]
Yeah, if you send over the file I can take a look.

**Comment by elgamble** [comment]
Cheers man! Appreciated muchly

[test1.fla.zip](https://github.com/TomByrne/Flash2Svg/files/523876/test1.fla.zip)

**Comment by TomByrne** [comment]
I have fixed the issue with the with the overlapping frames, the fix will be included in the next release (v3,48) which should be released in the next few weeks.
If you want to export it correctly in the meantime, try turning the "Tween final frame into first frame." option on.

Regarding the original issue you had, I'd need an FLA with set up in this way to be able to resolve.
