### ISSUE TITLE
Why are they only working in webkit?

### ISSUE THREAD

**Issue by keithpickering** [TomByrne/Flash2Svg#27]
Take a look at the following files:

https://minus.world/images/smilies/svg/mw_popcorn.svg
https://minus.world/images/smilies/svg/mw_yes.svg
https://minus.world/images/smilies/svg/mw_no.svg

All three were exported using this same tool. The first one works fine in both Firefox and Chrome, as well as mobile browsers. However, the second two ONLY work in webkit. In firefox they're both frozen on the first frame.

How can I debug these? Thanks.

**Comment by TomByrne** [comment]
Hi Keith,
Looks like FF has trouble with duration attributes that lack a leading zero (when the animation runs for less than a second).

I have opened a bug report with Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1317652

I have added a workaround for this issue in v3.49

**Comment by keithpickering** [comment]
A flawless, simple fix - you are a lifesaver. Thank you for the fantastic tool!
