### ISSUE TITLE
No image after timeline has finished

### ISSUE THREAD

**Issue by samelie** [TomByrne/Flash2Svg#29]
Hi, cool library Tom
There might be a simple thing I am missing.
I do not want the svg to loop, so I leave the option unchecked. Doing this causes, once the timeline has played out, the last frame to be blank.
I've tried forcing the timeline frame range too.
It looks fine when it loops.
Using the 3.50 release
[lock.fla.zip](https://github.com/TomByrne/Flash2Svg/files/647463/lock.fla.zip)

**Comment by TomByrne** [comment]
I've looked into this, it should be fixed in version 3.51.
