### ISSUE TITLE
colors get a bit washed out

### ISSUE THREAD

**Issue by aaronionellwinkler** [TomByrne/Flash2Svg#33]
I am exporting a simple loader and on export, the colors seem to be getting lighter.
thanks

**Comment by TomByrne** [comment]
Hi Aaron,
The plugin now leverages the built-in SVG export for vector path information, so I don't really have control over this. Also, are you sure it is the SVG and not the viewer being used to render the SVG.
You can confirm this by looking at the Hex values in the SVG and comparing them to those in Flash/Animate.

Either way, there's little I can do in the tool to correct this.
Maybe you could apply an SVG filter to correct it, but this would have performance implications.
