### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by laisk** [TomByrne/Flash2Svg#35]
Hi Tom,
I was trying out for the first time the plugin and I receive this error:
doNextTimeline: 0 file:///Macintosh%20HD/Users/lais.kantor.caserta/Desktop/plus+check.svg
Error: Invalid JavaScript object. The original object may have been deleted or the document may have been closed.

Not sure if there is something that I can do to fix. I attach the file so you can see it.

Thanks a lot!
[plus+check.fla.zip](https://github.com/TomByrne/Flash2Svg/files/1148757/plus.check.fla.zip)

**Comment by laisk** [comment]
Hi Tom,
I transform it all in a frame by frame animation and it worked :)
I guess the issue is with shape animation.

**Comment by TomByrne** [comment]
Hi,
I've added a workaround for this in v3.53.
If an element becomes 'unavailable', it will be ignored with a warning message (instead of killing the whole export).

**Comment by federicomazza1976** [comment]
Hi Tom, firstly thank you for your works! Second: do the plugin still works with the last version of Adobe Animate? I just tried to use it but I receive an output error: TypeError: svgXml.defs[0] is undefined
Can I do something to have my little poor svg animation :( I tried to convert the motion in frame by frame but it doesent works, let me know please. Many thanks!
