### ISSUE TITLE
Last frame glitch?

### ISSUE THREAD

**Issue by katopz** [TomByrne/Flash2Svg#4]
Test with Mac+chrome Version 40.0.2214.91 (64-bit) via http://www.tbyrne.org/smil-test-page

![screen shot 2015-01-25 at 12 19 41 pm](https://cloud.githubusercontent.com/assets/97060/5890461/ac00ba3e-a48e-11e4-921f-9dfb8d7d8c07.png)

this happens when animation stop

**Comment by TomByrne** [comment]
This was fixed a long time ago and simply needed to be reexported, which I've now done.
