### ISSUE TITLE
Error: The function breakApart() is currently unavailable.

### ISSUE THREAD

**Issue by 1GR3** [TomByrne/Flash2Svg#40]
The svg animation is not generated and the fla file animation is broken as well after SVG Export.
Please take a look:
https://www.dropbox.com/s/ztg52qvktspn4l6/Kybette%20-%20treepose2.fla?dl=0
Thank you in advance!

**Comment by 1GR3** [comment]
I fixed it by breaking every possible group :)

**Comment by TomByrne** [comment]
I've looked into this and refactored part of the Shape creation.
It'a a bit simpler now, and should be less buggy.
Let me know if it gives you any trouble (v3.55).
