### ISSUE TITLE
 reference to undefined XML name @id

### ISSUE THREAD

**Issue by 1GR3** [TomByrne/Flash2Svg#41]
ReferenceError: reference to undefined XML name @id
Failed to load SVG for embedding

I have the latest version installed in Adobe Animate CC.
Can you please, take a look?

https://www.dropbox.com/s/3u8z2i9f99p9igj/kybee%20-%20are%20you%20still%20there.fla?dl=0

**Comment by TomByrne** [comment]
Hey,
I'll check this out when I get a chance, but in the meantime, would you be able to test it with v3.55?

**Comment by TomByrne** [comment]
This should be resolved in v3.56.
Sorry it took so long to look into this.
