### ISSUE TITLE
Output Format Type: SVG Images | Breaks on gradients?

### ISSUE THREAD

**Issue by Jkarssen** [TomByrne/Flash2Svg#42]
Animate version: CC. 2017.2 Release Build 16.2.0.24
SVG Animation version: v3.54

Currently I am testing the usage of your add-on to generate the separate 'SVG Images', so later on with code I can put them together to animate to this way be compatible with IE.

Now when having a flat object being animated works file, and it generates all the images perfect.
Yet, when I have an object with a gradient, it seems to work on frame '0', but from frame '1' and forward all objects
containing a gradient are black objects.

Now I feel I have tried every possible combination or option in the SVG Animation export, but it keeps breaking on gradient objects.
Is this a bug of am I missing a setting?

Thanks for the add-on and help
![svg_animation](https://user-images.githubusercontent.com/34652260/35511377-e5651dda-04fb-11e8-93c4-491d92c4d5c9.JPG)

**Comment by Robinfr** [comment]
I checked this out for a bit, and it seems all of the SVGs after the first frame are referencing the gradients in the first file and ALSO creating the gradients AGAIN with a new name.

**Comment by TomByrne** [comment]
This should be fixed in v3.56
