### ISSUE TITLE
broken with version 19 of Adobe Animate CC

### ISSUE THREAD

**Issue by nelhop** [TomByrne/Flash2Svg#45]
Since version 19 of Adobe Animate CC the Plugin seems to be broken. Exports which worked before are now completely destroyed.

Is there any chance the Plugin will be updated to be compatible with the current CC Version?

**Comment by kyle-chivers** [comment]
Ah, that's a shame. I'll have stick to an older version.  👍

**Comment by dashayuyoulaiyouqu** [comment]
> 啊，这太遗憾了。我会坚持使用旧版本。 👍

请问您用的是哪个版本的flash？

**Comment by TomByrne** [comment]
Please try with v3.58.
This fixes a regression that Animate 2019 introduced (relating to transforms on shapes).
I have noticed some other strange behaviour in 2019 that I haven't had a chance to look into yet.

**Comment by apellaman** [comment]
Still not working with the 3.58..
