### ISSUE TITLE
couldn't start on СС and СС2014

### ISSUE THREAD

**Issue by redscotina** [TomByrne/Flash2Svg#5]
tested on 3 versions flash cc\cc2014 and worked only on cs6,
in cc/cc2014 in window>extension no have plug

**Comment by HBehrens** [comment]
same result on cc2014.1 (14.1.0.96). Extension Manager installs but Window -> Extensions only shows "Adobe Color themes".

**Comment by TomByrne** [comment]
I have tested on Mac and Windows for CS6, CC and CC 2014.
So I'll need some more info.

Which OS are you guys running?
Can either of you check whether a folder called "org.tbyrne.SvgAnimationForFlash" exists on your hard drive (including hidden directories). It should be somewhere within the hidden AppData folder on Windows (can't remember about Mac).

Also, can you confirm that you've installed the CC version of the plugin and not the CS version (which will successfully install on CC).

**Comment by HBehrens** [comment]
I am running cc2014.1 (14.1.0.96) on OS X 10.9.5. After your comment, @TomByrne I tried your v3.2 and v3.1 for CC and CS and got these surprising results:
- flash2svg.CC.v3.2.zxp (no menu entry)
- flash2svg.CS.v3.2.zxp (fully working UI)
- flash2svg.CC.v3.1.zxp (no menu entry)
- flash2svg.CS.v3.1.zxp (fully working UI)

No folder for `find . | grep org.tbyrne.SvgAnimationForFlash` on `~/Library`.

When I try to export an image as SVG sequence I get:

```
... (removed earlier output)
doNextTimeline: 13 file:///Macintosh%20HD/Users/behrens/Documents/flash/test_1/13.svg
TypeError: timeline.libraryItem is null
TypeError: xml is undefined
endProgress
 The 'Document.editScene' JS API is not supported for HTML5 Canvas.
Error:  The 'Document.editScene' JS API is not supported for HTML5 Canvas.
```

when exporting as Animated SVG I get:

```
doNextTimeline: 0 file:///Macintosh%20HD/Users/behrens/Documents/flash/test_1.svg
 The 'Document.editScene' JS API is not supported for HTML5 Canvas.
Error:  The 'Document.editScene' JS API is not supported for HTML5 Canvas.
TypeError: document is undefined
endProgress
 The 'Document.editScene' JS API is not supported for HTML5 Canvas.
Error:  The 'Document.editScene' JS API is not supported for HTML5 Canvas.
```

It seems like the _wrong_ CS version shows up but expects an incompatible object model when processing the data.

Anything I can help you with?

**Comment by redscotina** [comment]
i use windows 7
I didn't find "org.tbyrne.SvgAnimationForFlash"

**Comment by redscotina** [comment]
I didn't find "org.tbyrne.SvgAnimationForFlash"

**Comment by TomByrne** [comment]
Would you be able to try this new installer and let me know if it works?
Yeah, the CS version should work across everything, it just has a much
crappier UI.

If you want me to fix those errors you're seeing, send me the FLA and I'll
see what I can do.

**Comment by TomByrne** [comment]
Would you be able to try this new installer and let me know if it works?

**Comment by redscotina** [comment]
I reinstalled flash 2014, same result

**Comment by HBehrens** [comment]
Reinstalled (same version of OS X and Flash), doesn't show up on the menu anymore.

**Comment by redscotina** [comment]
update to 3.5 on flash 2014, same result, issue not fixed

**Comment by TomByrne** [comment]
I have a contact at Adobe looking into this.

**Comment by nicasi** [comment]
I also don't find the panel under Venster -> Extensies (I use a Dutch version, silly me)

I'm on Windows 8.1 with Flash cc 2014 build 14.2.0.20

I did find the extension in my filesystem:
C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\org.tbyrne.SvgAnimationForFlash

**Comment by TomByrne** [comment]
Hi Nicasi,
Would you be able to try this installer and let me know if it works for you?

**Comment by nicasi** [comment]
Hi Tom,
I don't know which installer you are refering too.
fyi, I installed your latest release via the Adobe extension manager (Flash2Svg.v3.7.0.zxp)

**Comment by TomByrne** [comment]
Oh, sorry. The zxp file that's attached to the last email.

**Comment by nicasi** [comment]
Hmmmm, I don't see it on this github page. The file is also not in my mailbox. Me thinks github only allows attachment of image files... or maybe i'm just blind?

I would love to help and try the new installer. Can you send it some other way?

**Comment by TomByrne** [comment]
Ah I see, send me an email to work@tbyrne.org, I'll reply with the plugin.

**Comment by imsky** [comment]
This isn't working for me. Adobe Extension Manager reports "this extension can not be installed, it requires Flash version 11 or greater." for 3.2->3.13 versions.

**Comment by TomByrne** [comment]
Hey imsky,
What version of Flash, Ext. Manager and your OS are you running?

**Comment by imsky** [comment]
Ext Manager: 6.0.8.28
Flash: 14.2.0
OS: Mac OS X 10.10.3

**Comment by TomByrne** [comment]
Can you update to Ext. Manager 7 and try again for me?
