### ISSUE TITLE
Signature not valid

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [TomByrne/Flash2Svg#57]
Hi,

I'm trying to install the ZXP 3.36 for Flash Pro CS6 but block the installation saying that the signature is not valid,
despite of I unchecked all warnings in preferences.

Thanks

**Comment by ROBERT-MCDOWELL** [comment]
problem solved by installing it manually, explanation from
http://www.tbyrne.org/manually-installing-flash2svg
Happy new year Tom, we hope freedom and justice will win asap!

**Comment by TomByrne** [comment]
For others experiencing this issue, it may be that you previously had installed the plugin from the Adobe add-ons site, which replaces the plugin's signature with it's own. To get around this, uninstall the previous version before installing the version from Github.

**Comment by TomByrne** [comment]
@ROBERT-MCDOWELL, not sure what "we hope freedom and justice will win asap" means.

If it means you're red-pilled, great job on being an adult living in a LARP.

**Comment by ROBERT-MCDOWELL** [comment]
no pills at all, i know their game since 20 years now. it's just the logical consequence of how psychopaths with power on normal people work.

**Comment by TomByrne** [comment]
As I said, great job.

**Comment by ROBERT-MCDOWELL** [comment]
I would say great job to you! :), don't give up the work done during all these years. I do on my side too!
