### ISSUE TITLE
MotionTweens don't get exported

### ISSUE THREAD

**Issue by grossmann** [TomByrne/Flash2Svg#6]
Hi, I am using Win7 with CS5 and V 3.2 of flash2svg and tried to export a flash animation with motion tweens. The result was alway only one frame but no animation. Changing the tween to a classic tween did export the animation. Is there a way to get te export working with motion tweens?
Thanks for your help and this nice extension.

**Comment by TomByrne** [comment]
Hi,
The tool only supports classic tweens, sorry.

**Comment by grossmann** [comment]
Thank you for your fast reply and the information. I thought motion tweens are supported because of the option "Flatten motion tweens". But I think this means something different than the terminology adobe uses to distinct between "classic tweens" and "motion tweens".
So I have to convert my tweens to "classic" tweens (or frame by frame animations) and then it should work.

**Comment by petergoes** [comment]
Is there a chance that motion tweens are going to be supported in the future?

**Comment by TomByrne** [comment]
I don't think so, sorry.
With Chromium's recent deprecation of SMIL, it's hard to justify much unpaid work on the tool.
Motion Tweens should still export, although they'll be converted to keyframes.

**Comment by petergoes** [comment]
If it is SMIL or something else, does not really matter for me in this case. But to have Motion Tweens supported would be highly appreciated.

Classic tweens are just to limited for me, I want to go nuts with easing :)

**Comment by TomByrne** [comment]
Hey Peter,
You were correct in saying that the current version did export newer type Motion Tweens.
I have added partial support to v3.28 (in releases).
What this means is that they will be exported, but they will first be converted to keyframes.
This means that the resulting file is a little bigger than it could be with full support.
I doubt I will ever have the time to add this type of full support, but hopefully the partial support I've added will be sufficient.

**Comment by petergoes** [comment]
When I continue with the project, I will dive a little deeper in the partial support. Will not be for another 3 weeks though.

I do not care that much about the bigger file size, when gzipped, that does not really matter because of the repetition in the resulting code.
