### ISSUE TITLE
Can't install in Adobe Animate 24.0

### ISSUE THREAD

**Issue by hrvstr** [TomByrne/Flash2Svg#63]
Hi, I am experiencing issues while trying to install this extension in Adobe Animate 24.0 on macOS 14.5. I have attempted both automatic and manual installation methods, but neither has been successful.

ZXPInstaller fails with this error:
`stdout: Failed to install, status = -164!`

I also tried the other installers but no dice there too.

When I install manually the extension does not show up under "Window > Extensions".

Can anybody confirm that it's not working anymore or recommend an older version of Animate that is still supported?

Thanks!

**Comment by TheBlurrypixel** [comment]
This repo hasn't been updated in years. I created a fork to address this.
https://github.com/TheBlurrypixel/Flash2Svg/tree/blurrypixel_patch

**Comment by hrvstr** [comment]
Awesome, thank you! Do I have to build this myself?

I tried to download the latest release but it won't show up either:
https://github.com/TheBlurrypixel/Flash2Svg/releases/tag/v3.58

**Comment by TheBlurrypixel** [comment]
No, make sure you are in the blurrypixel_patch branch and then download from the bin folderOn Aug 1, 2024, at 10:00 AM, Richard Muhler ***@***.***> wrote:﻿
Awesome, thank you! Do I have to build this myself?
I tried to download the latest release but it won't show up either:
https://github.com/TheBlurrypixel/Flash2Svg/releases/tag/v3.58

**Comment by hrvstr** [comment]
Thank you, I found the correct file now and got it working. I also had to extract the ZXP and install the ZXP inside the `HTML` folder to make it work.
