### ISSUE TITLE
Can't install on Flash CC 2015

### ISSUE THREAD

**Issue by jackfreak** [TomByrne/Flash2Svg#8]
When I try to install the extension I get this error message: "This extension cannot be installed, it requires Flash version 11 or greater"

Im on Windows 7 (64) using Flash CC 2015 (15.0.1.179)

![2015-09-07_215559](https://cloud.githubusercontent.com/assets/1307629/9724301/4ed568d6-55ab-11e5-9b68-847de39d091f.png)

**Comment by emlyn-Resn** [comment]
I'm getting the same on Win 10 (64), and Flash CC 2015

**Comment by emlyn-Resn** [comment]
Looks like you can install it via the addons site.. https://creative.adobe.com/addons/producers/24037

Guess it's a problem with the CC extensions manager?

**Comment by jackfreak** [comment]
I wasn't  aware of that add-on site! =)

Sadly I tried to install it from there and even though it says INSTALLED it doesn't show when I open Flash CC Window->Extensions.

**Comment by emlyn-Resn** [comment]
Have you made sure that you've enabled 'sync files' in creative cloud?

**Comment by jackfreak** [comment]
Yeap, no luck. Thanks anyway =)

**Comment by jackfreak** [comment]
I was finally able to install it =)

If anyone else is having this issue try these steps: 
1- Remove the addon via the addon site (in "My add-ons"), wait a couple of minutes so it will fully uninstall.
2- Close the Adobe CC app.
3- Install the add-on again from the add-on site.
4- Restart the Adobe CC app with Admin priviledges ("Run as Administrator"), it will attempt to install all pending add-ons.

See https://forums.adobe.com/thread/1505311

**Comment by ghost** [comment]
I couldn't install with 'Adobe Extension Manager' and 'Creative Cloud addons', but I've installed it with https://github.com/cjgammon/SnapSVG-Animator 'Comand Line Tool' method and works!

You have to download 'Adobe Extension Command Line Tool':
Mac OS:  http://www.adobeexchange.com/ExManCmd_mac.zip
Windows: http://www.adobeexchange.com/ExManCmd_win.zip

And run the command:
Mac OS: ./Contents/MacOS/ExManCmd --install myaddon.zxp
Windows: ExManCmd.exe /install myaddon.zxp
